// Default content configuration for all pages and sections

export const defaultSiteContent: Record<string, any> = {
  home: {
    hero: {
      title: 'NOUS CONSTRUISONS VOS RÊVES',
      subtitle: 'De la vision aux fondations. Des fondations à la réalité.',
      bgImage: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1920&q=80',
      btnPrimaryText: 'Demander un devis',
      btnPrimaryHref: '/contact',
      btnSecondaryText: 'Nos réalisations',
      btnSecondaryHref: '/realisations',
    },
    intro: {
      title1: "BÂTIR AUJOURD'HUI.",
      title2: 'IMAGINER DEMAIN.',
      text: 'MPANORINA NOFY est une entreprise de construction ambitieuse, fondée avec la conviction que chaque projet mérite excellence et engagement. Spécialisés dans le gros œuvre et la construction de bâtiments à Madagascar, nous transformons les visions architecturales en réalités solides et durables.',
      image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80',
      badgeSubtitle: 'MPANORINA NOFY',
      badgeTitle: 'Excellence & Gros Œuvre à Madagascar',
      point1Title: 'Gros Œuvre & Solidité',
      point1Desc: 'Normes de construction strictes',
      point2Title: 'Savoir-Faire Premium',
      point2Desc: 'Équipe qualifiée & rigueur',
    },
    video: {
      title: 'CHAQUE PROJET COMMENCE PAR UNE VISION.',
      bgImage: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1920&q=80',
    },
    cta: {
      title: 'PRÊT À CONSTRUIRE VOTRE PROJET ?',
      subtitle: 'Transformons votre vision en réalité.',
      bgImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1920&q=80',
      btnText: 'Demander un devis',
      btnHref: '/contact',
    },
  },
  about: {
    hero: {
      title: "L'AMBITION DE CONSTRUIRE",
      subtitle: 'Notre Histoire',
      bgImage: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=1920&q=80',
    },
    story: {
      title: 'Une vision née d’une passion',
      p1: "Fondée avec la volonté de redéfinir les standards de la construction à Madagascar, MPANORINA NOFY s'est imposée comme un acteur de référence dans le secteur du bâtiment et des travaux de gros œuvre.",
      p2: 'Notre nom, qui signifie "Bâtisseur de Rêves", incarne notre mission fondamentale : transformer les aspirations architecturales de nos clients en structures solides, durables et élégantes.',
      p3: 'De la conception aux finitions, notre équipe d’ingénieurs, conducteurs de travaux et artisans qualifiés met en œuvre un savoir-faire rigoureux et des techniques modernes adaptées aux spécificités de Madagascar.',
      image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80',
    },
    vision: {
      visionTitle: 'Notre Vision',
      visionText: 'Devenir le partenaire de référence pour la construction durable et moderne à Madagascar, en alliant innovation technique, respect des normes internationales et valorisation des compétences locales.',
      missionTitle: 'Notre Mission',
      missionText: 'Bâtir des structures d’excellence qui traversent le temps, en offrant à nos clients un accompagnement personnalisé, une transparence totale et une rigueur sans compromis.',
    },
  },
  services: {
    hero: {
      title: 'NOTRE SAVOIR-FAIRE',
      subtitle: 'Services & Expertises',
      bgImage: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1920&q=80',
    },
    items: [
      {
        id: 'gros-oeuvre',
        number: '01',
        title: 'GROS ŒUVRE',
        description: 'Réalisation complète des structures porteuses de vos bâtiments avec rigueur et précision.',
        longDescription: 'Notre expertise en gros œuvre couvre l\'ensemble des travaux de structure : fondations, élévation des murs porteurs, dalles, poteaux, poutres et toitures. Nous garantissons la solidité et la durabilité de chaque construction grâce à des techniques éprouvées et des matériaux de qualité.',
        image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80',
        features: ['Fondations et terrassement', 'Élévation des murs porteurs', 'Dalles et planchers', 'Structures en béton armé', 'Charpente et toiture', 'Assainissement'],
      },
      {
        id: 'construction-batiments',
        number: '02',
        title: 'CONSTRUCTION DE BÂTIMENTS',
        description: 'Construction clé en main de bâtiments résidentiels, commerciaux et industriels.',
        longDescription: 'De la première pierre à la remise des clés, nous prenons en charge la construction complète de vos bâtiments. Résidences, immeubles commerciaux, bâtiments industriels — chaque projet bénéficie de notre savoir-faire et de notre engagement qualité.',
        image: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=800&q=80',
        features: ['Bâtiments résidentiels', 'Immeubles commerciaux', 'Bâtiments industriels', 'Constructions publiques', 'Villas et maisons individuelles', 'Immeubles collectifs'],
      },
      {
        id: 'renovation-rehabilitation',
        number: '03',
        title: 'RÉNOVATION ET RÉHABILITATION',
        description: 'Redonner vie aux bâtiments existants tout en respectant leur caractère et leur histoire.',
        longDescription: 'Nous redonnons vie aux bâtiments existants grâce à nos services de rénovation et de réhabilitation. Que ce soit pour moderniser un espace, renforcer une structure ou transformer une propriété, notre équipe intervient avec expertise et soin du détail.',
        image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&q=80',
        features: ['Rénovation complète', 'Renforcement structural', 'Mise aux normes', 'Extension de bâtiments', 'Réhabilitation de façades', 'Aménagement intérieur'],
      },
      {
        id: 'etude-conception',
        number: '04',
        title: 'ÉTUDE ET CONCEPTION',
        description: 'Accompagnement technique et architectural dès la phase de conception de votre projet.',
        longDescription: 'Notre bureau d\'études accompagne vos projets dès la phase de conception. Études de faisabilité, plans architecturaux, calculs de structure — nous mettons notre expertise technique au service de votre vision pour garantir un projet réalisable, optimisé et conforme.',
        image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80',
        features: ['Étude de faisabilité', 'Plans architecturaux', 'Calculs de structure', 'Études de sol', 'Métrés et devis', 'Suivi de chantier'],
      },
      {
        id: 'travaux-construction',
        number: '05',
        title: 'TRAVAUX DE CONSTRUCTION',
        description: 'Tous types de travaux de construction pour concrétiser vos projets les plus ambitieux.',
        longDescription: 'De l\'aménagement de terrain aux finitions, nous réalisons l\'ensemble des travaux nécessaires à la concrétisation de vos projets. Notre équipe qualifiée et notre parc matériel nous permettent d\'intervenir sur des chantiers de toute envergure.',
        image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=1200&q=80',
        features: ['Terrassement et VRD', 'Maçonnerie', 'Béton armé', 'Coffrage et ferraillage', 'Enduits et finitions', 'Aménagements extérieurs'],
      },
    ],
  },
  contact: {
    phone: '+261 34 00 000 00',
    email: 'contact@mpanorina-nofy.mg',
    address: 'Antananarivo',
    fullAddress: 'Antananarivo, Madagascar',
    whatsapp: '261340000000',
    hours: 'Lun - Ven : 8h00 - 17h00',
    facebook: 'https://facebook.com/mpanorinanofy',
    instagram: 'https://instagram.com/mpanorinanofy',
    linkedin: 'https://linkedin.com/company/mpanorinanofy',
  },
  stats: {
    items: [
      { value: 50, prefix: '+', suffix: '', label: 'Projets Réalisés' },
      { value: 10, prefix: '+', suffix: '', label: "Années d'Expérience" },
      { value: 100, prefix: '', suffix: '%', label: 'Satisfaction Client' },
      { value: 25, prefix: '+', suffix: '', label: 'Experts & Ouvriers' },
    ],
  },
};
